import type { Metadata } from "next";
import { Jost } from 'next/font/google'
import "./globals.css";


export const metadata: Metadata = {
  title: "Weather App",
  description: "Generated by create next app",
};

const jostFont = Jost({
  subsets: ['latin'],
  weight: ['300', '500', '800'],
  variable: '--font-jost'
})


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body
        className={`${jostFont.variable}antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
